# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem 'mysql2', github: 'brianmario/mysql2'
gem 'mysql2-cs-bind', github: 'kamipo/mysql2-cs-bind'
gem 'symbol-fstring', require: 'fstring/all'
gem "unicorn"

gem 'newrelic_rpm', '6.11.0.365'
